library(lubridate) # manipulation de dates
library(tibble) # affichage des données

# copie du data.table flats
apparts <- flats

# conversions en Dates
apparts$last_scraped <- ymd(apparts$last_scraped)
apparts$host_since   <- ymd(apparts$host_since)
# mise en forme (texte) du code postal
# génère un message Warning "NAs introduced by coercion"
# car zipcode contient des valeurs texte sur lesquelles bute 
# la fonction as.numeric
apparts$zipcode      <- formatC(as.numeric(apparts$zipcode),
                                big.mark = " ",
                                format="d")
# transformation en facteur du type de logement loué
apparts$room_type    <- factor(apparts$room_type)

# on constate dans le descriptif que les types sont les bons
glimpse(apparts)
# Observations: 51,494
# Variables: 21
# $ id                     <int> 4867396, 7704653, 27250...
# $ listing_url            <chr> "https://www.airbnb.com...
# $ last_scraped           <date> 2016-07-03, 2016-07-04...
# $ host_id                <int> 9703910, 35777602, 1394...
# $ host_name              <chr> "Matthieu", "Claire", "...
# $ host_since             <date> 2013-10-29, 2015-06-14...
# $ host_location          <chr> "Nantes, Pays de la Loi...
# $ neighbourhood          <chr> "Batignolles", "Champs-...
# $ neighbourhood_cleansed <chr> "Batignolles-Monceau", ...
# $ zipcode                <chr> "75 017", "75 017", "75...
# $ property_type          <chr> "Apartment", "Apartment...
# $ room_type              <chr> "Entire home/apt", "Ent...
# $ accommodates           <int> 2, 4, 2, 2, 2, 3, 4, 2,...
# $ bathrooms              <dbl> 1.0, 2.0, 1.0, 1.0, 1.0...
# $ bedrooms               <int> 1, 2, 1, 1, 1, 2, 2, 1,...
# $ beds                   <int> 1, 3, 1, 1, 1, 2, 2, 1,...
# $ price                  <dbl> 60, 200, 80, 60, 50, 10...
# $ number_of_reviews      <int> 1, 0, 1, 1, 2, 4, 14, 2...
# $ review_scores_rating   <int> 100, NA, 80, 80, 100, 1...
# $ cancellation_policy    <chr> "flexible", "flexible",...
# $ amenities              <chr> "TV|Cable TV|Internet|W...
