library(tibble) # affichage des données

# copie du data.table flats
apparts <- flats

# type des variables à l'origine
glimpse(apparts)
# Observations: 51,494
# Variables: 23
# $ id                     <int> 9842051, 13420043, 128...
# $ listing_url            <chr> "https://www.airbnb.co...
# $ last_scraped           <chr> "2016-07-03", "2016-07...
# $ host_id                <int> 50537853, 76489012, 44...
# $ host_name              <chr> "Ruth", "Simon", "Coco...
# $ host_since             <chr> "2015-12-04", "2016-06...
# $ host_location          <chr> "Paris, Île-de-France,...
# $ neighbourhood          <chr> "", "", "", "", "", ""...
# $ neighbourhood_cleansed <chr> "Popincourt", "Gobelin...
# $ zipcode                <chr> "", "", "", "", "", ""...
# $ property_type          <chr> "Apartment", "Apartmen...
# $ room_type              <chr> "Shared room", "Privat...
# $ accommodates           <int> 1, 1, 1, 1, 1, 1, 1, 1...
# $ bathrooms              <dbl> 1.0, 1.0, 0.5, 1.0, 1....
# $ bedrooms               <int> 1, 1, 1, 1, 1, 1, 1, 1...
# $ beds                   <int> 1, 1, 1, 1, 1, 1, 1, 1...
# $ price                  <dbl> 19, 20, 20, 20, 20, 20...
# $ number_of_reviews      <int> 4, 1, 5, 7, 2, 6, 11, ...
# $ review_scores_rating   <int> 85, 80, 65, 89, 90, 87...
# $ cancellation_policy    <chr> "strict", "flexible", ...
# $ amenities              <chr> "Wireless Internet|Kit...

# transformation en facteurs de 6 variables à la fois
apparts[,c("neighbourhood",
           "neighbourhood_cleansed",
           "zipcode",
           "property_type",
           "room_type",
           "cancellation_policy")] <- 
  as.data.table(lapply(apparts[,.(neighbourhood,
                                  neighbourhood_cleansed,
                                  zipcode,
                                  property_type,
                                  room_type,
                                  cancellation_policy)],
                       FUN = as.factor))
# vérification des nouveaux types <fctr>
glimpse(apparts)
# Observations: 51,494
# Variables: 21
# $ id                     <int> 9842051, 13420043, 128...
# $ listing_url            <chr> "https://www.airbnb.co...
# $ last_scraped           <chr> "2016-07-03", "2016-07...
# $ host_id                <int> 50537853, 76489012, 44...
# $ host_name              <chr> "Ruth", "Simon", "Coco...
# $ host_since             <chr> "2015-12-04", "2016-06...
# $ host_location          <chr> "Paris, Île-de-France,...
# $ neighbourhood          <fctr> , , , , , , , , , , B...
# $ neighbourhood_cleansed <fctr> Popincourt, Gobelins,...
# $ zipcode                <fctr> , , , , , , , , , , ,...
# $ property_type          <fctr> Apartment, Apartment,...
# $ room_type              <fctr> Shared room, Private ...
# $ accommodates           <int> 1, 1, 1, 1, 1, 1, 1, 1...
# $ bathrooms              <dbl> 1.0, 1.0, 0.5, 1.0, 1....
# $ bedrooms               <int> 1, 1, 1, 1, 1, 1, 1, 1...
# $ beds                   <int> 1, 1, 1, 1, 1, 1, 1, 1...
# $ price                  <dbl> 19, 20, 20, 20, 20, 20...
# $ number_of_reviews      <int> 4, 1, 5, 7, 2, 6, 11, ...
# $ review_scores_rating   <int> 85, 80, 65, 89, 90, 87...
# $ cancellation_policy    <fctr> strict, flexible, mod...
# $ amenities              <chr> "Wireless Internet|Kit...

# autre écriture, même résultat
apparts <- flats
apparts[, c("neighbourhood",
            "neighbourhood_cleansed",
            "zipcode",
            "property_type",
            "room_type",
            "cancellation_policy") := 
          lapply(apparts[,.(neighbourhood,
                            neighbourhood_cleansed,
                            zipcode,
                            property_type,
                            room_type,
                            cancellation_policy)],
                 FUN = as.factor)]
